# Makefile para compilar y ejecutar el testbench 
receptor: 		testbench.v 
			iverilog testbench.v 
			vvp a.out 
			gtkwave ondas.gtkw	# Abre el archivo gtkwave con las señales ya desplegadas y ordenadas.

clean: 
			rm .*.swp






:wq
