tarea: testbench.v          # Archivos requeridos.
	iverilog testbench.v	# Corre Icarus.
	vvp a.out				# Corre la simulacion.
	gtkwave ondas.gtkw		# Abre el archivo gtkwave con las señales ya desplegadas y ordenadas.

    
