tarea: testbench_transmit.v          # Archivos requeridos.
	iverilog testbench_transmit.v				# Corre Icarus.
	vvp a.out									# Corre la simulacion.
	gtkwave gtkwave_ordenadas_transmit.gtkw		# Abre el archivo gtkwave con las señales ya desplegadas y ordenadas.

    
